---
version: '3.7'

services:
  osticket-db:
    image: mariadb
    container_name: osticket-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=osticket-db

      - ROOT_PASS=securepassword
      - DB_NAME=osticket
      - DB_USER=osticket
      - DB_PASS=password
      - MYSQL_ROOT_PASSWORD=secret4321
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=osticket mariadb
  
  osticket-app:
    image: osticket/osticket
    container_name: osticket-app
    volumes:
      - ./data/:/www/osticket
      - ./logs/:/www/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=osticket-app

      - CRON_INTERVAL=10

      - DB_HOST=osticket-db
      - DB_NAME=osticket
      - DB_USER=osticket
      - DB_PASS=password

      - MYSQL_HOST=osticket-db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=osticket mariadb

      - SMTP_HOST=localhost
      - SMTP_PORT=25
      - SMTP_FROM=osticket@example.com
      - SMTP_TLS=0
      - SMTP_USER=osticket@example.com
      - SMTP_PASS=password

      - INSTALL_SECRET=somerandomlargecharacterstring
      - INSTALL_EMAIL=osticket@example.com
      - INSTALL_NAME=OSTicket Helpdesk

      - ADMIN_FIRSTNAME=Admin
      - ADMIN_LASTNAME=User
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_USER=ostadmin
      - ADMIN_PASS=Password123
